openapi: 3.0.1
info:
  title: Products API
  description: API for managing products
  version: 1.0.0
servers:
  - url: https://localhost:8000
    description: ハンバーガー注文サイト管理 server
paths:
  /products:
    get:
      summary: Get all products
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Create a new product
      requestBody:
        description: Product to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Product created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
  /products/{id}:
    get:
      summary: Get a product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
    put:
      summary: Update a product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: Product to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Product updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
    delete:
      summary: Delete a product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Product deleted
        '404':
          description: Product not found
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
        slug:
          type: string
          description: Product tag name (alphanumeric)
        name:
          type: string
          description: Product name
        description:
          type: string
          description: Product description
        image:
          type: string
          description: Product image URL
        price:
          type: number
          format: float
          description: Price
        sortid:
          type: integer
          description: Sort ID
        display:
          type: boolean
          description: Display status
        created_at:
          type: string
          format: date-time
          description: Creation date
        updated_at:
          type: string
          format: date-time
          description: Update date
        deleted_at:
          type: string
          format: date-time
          description: Deletion flag
      required:
        - id
        - slug
        - name
        - price
        - sortid
        - display
        - created_at
        - updated_at
        - deleted_at
